name: 'Continuous Delivery'
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - develop

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/1052423921685/locations/global/workloadIdentityPools/github-actions/providers/github
          service_account: github-deployer@latam-challenge-506113.iam.gserviceaccount.com

      - name: Verify authentication
        run: gcloud auth list