name: 'Continuous Delivery'
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - develop

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: YOUR_PROVIDER_RESOURCE_NAME
          service_account: YOUR_SERVICE_ACCOUNT_EMAIL

      - name: Verify authentication
        run: gcloud auth list